package local;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * Interfaz para uso local del programa. Muestra el contenido de la cinta,
 * el contenido del avión y lo que están haciendo los empleados. Además, a
 * éstos últimos se les puede dar la orden de parar. Se puede consultar un
 * historial de eventos.
 * @author jorge
 */
public class LocalConsole extends javax.swing.JFrame {
    
    //Variables
    private boolean buttonPressed1, buttonPressed2, buttonPressed3 = false;
    ConveyorBelt belt = new ConveyorBelt(8);
    Plane plane = new Plane();
    Pass passage = new Pass();
    
    /**
     * Constructor.
     */
    public LocalConsole() {
        initComponents();
        setLocationRelativeTo(null); //Se centra en la pantalla.
        setSize(730, 550);    
        Console.setSize(730,550);
        //Asignación de elementos de interfaz a la cinta y al avión.
        belt.setText(jTextAreaBelt);
        belt.setProgress(jProgressBar2);
        plane.setText(jTextAreaPlane);
        plane.setProgress(jProgressBar1);
        //Estética
        jLabelLcorner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leftCorner.png")));
        jLabelRcorner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rightCorner.png")));
        recordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recordIcon.png")));      
        globalButton.setBorderPainted(false);
        globalButton.setFocusPainted(false);
        globalButton.setContentAreaFilled(false);
        //Inicialización del programa
        initialize();  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Console = new javax.swing.JPanel();
        jPanelPlane = new javax.swing.JScrollPane();
        jTextAreaPlane = new javax.swing.JTextArea();
        jPanelEmp2 = new javax.swing.JScrollPane();
        jTextAreaEmployee2 = new javax.swing.JTextArea();
        jPanelEmp1 = new javax.swing.JScrollPane();
        jTextAreaEmployee1 = new javax.swing.JTextArea();
        emp1Button = new javax.swing.JButton();
        emp2Button = new javax.swing.JButton();
        jPanelGlobal = new javax.swing.JPanel();
        globalButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelBelt = new javax.swing.JScrollPane();
        jTextAreaBelt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        recordButton = new javax.swing.JButton();
        jLabelLcorner = new javax.swing.JLabel();
        jLabelRcorner = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airport");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setForeground(new java.awt.Color(102, 102, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/planeIcon.png")).getImage());
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Console.setBackground(new java.awt.Color(0, 0, 20));
        Console.setForeground(new java.awt.Color(255, 255, 255));
        Console.setMinimumSize(new java.awt.Dimension(700, 700));
        Console.setPreferredSize(new java.awt.Dimension(1094, 500));
        Console.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPlane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelPlane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaPlane.setBackground(new java.awt.Color(0, 0, 0));
        jTextAreaPlane.setColumns(20);
        jTextAreaPlane.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jTextAreaPlane.setForeground(new java.awt.Color(102, 255, 255));
        jTextAreaPlane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jTextAreaPlane.setFocusable(false);
        jPanelPlane.setViewportView(jTextAreaPlane);

        Console.add(jPanelPlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 660, 50));

        jPanelEmp2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextAreaEmployee2.setBackground(new java.awt.Color(0, 0, 0));
        jTextAreaEmployee2.setColumns(20);
        jTextAreaEmployee2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jTextAreaEmployee2.setForeground(new java.awt.Color(102, 255, 255));
        jTextAreaEmployee2.setTabSize(0);
        jTextAreaEmployee2.setFocusable(false);
        jPanelEmp2.setViewportView(jTextAreaEmployee2);

        Console.add(jPanelEmp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 280, 35));

        jPanelEmp1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelEmp1.setHorizontalScrollBar(null);

        jTextAreaEmployee1.setBackground(new java.awt.Color(0, 0, 0));
        jTextAreaEmployee1.setColumns(20);
        jTextAreaEmployee1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jTextAreaEmployee1.setForeground(new java.awt.Color(102, 255, 255));
        jTextAreaEmployee1.setTabSize(0);
        jTextAreaEmployee1.setFocusable(false);
        jPanelEmp1.setViewportView(jTextAreaEmployee1);

        Console.add(jPanelEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 35));

        emp1Button.setBackground(new java.awt.Color(153, 0, 0));
        emp1Button.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        emp1Button.setForeground(new java.awt.Color(255, 255, 255));
        emp1Button.setText("Jorge");
        emp1Button.setBorder(null);
        emp1Button.setBorderPainted(false);
        emp1Button.setFocusable(false);
        emp1Button.setPreferredSize(new java.awt.Dimension(90, 15));
        emp1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp1ButtonActionPerformed(evt);
            }
        });
        Console.add(emp1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, 40));

        emp2Button.setBackground(new java.awt.Color(153, 0, 0));
        emp2Button.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        emp2Button.setForeground(new java.awt.Color(255, 255, 255));
        emp2Button.setText("Dani");
        emp2Button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emp2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp2ButtonActionPerformed(evt);
            }
        });
        Console.add(emp2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 120, 40));

        jPanelGlobal.setBackground(new java.awt.Color(153, 0, 0));
        jPanelGlobal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(222, 222, 222), new java.awt.Color(222, 222, 222)));
        jPanelGlobal.setForeground(new java.awt.Color(153, 0, 0));
        jPanelGlobal.setLayout(new javax.swing.BoxLayout(jPanelGlobal, javax.swing.BoxLayout.LINE_AXIS));

        globalButton.setBackground(new java.awt.Color(153, 0, 0));
        globalButton.setForeground(new java.awt.Color(255, 255, 255));
        globalButton.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        globalButton.setBorderPainted(false);
        globalButton.setMaximumSize(new java.awt.Dimension(40, 40));
        globalButton.setMinimumSize(new java.awt.Dimension(40, 40));
        globalButton.setPreferredSize(new java.awt.Dimension(40, 40));
        globalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalButtonActionPerformed(evt);
            }
        });
        jPanelGlobal.add(globalButton);

        Console.add(jPanelGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 40, 40));

        jPanel3.setBackground(new java.awt.Color(222, 222, 222));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Baggage on belt");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        Console.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 20));

        jPanelBelt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelBelt.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jPanelBelt.setFocusable(false);

        jTextAreaBelt.setBackground(new java.awt.Color(0, 0, 0));
        jTextAreaBelt.setColumns(20);
        jTextAreaBelt.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jTextAreaBelt.setForeground(new java.awt.Color(102, 255, 255));
        jTextAreaBelt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jTextAreaBelt.setCaretColor(new java.awt.Color(204, 255, 51));
        jTextAreaBelt.setFocusable(false);
        jPanelBelt.setViewportView(jTextAreaBelt);

        Console.add(jPanelBelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 660, 50));

        jPanel4.setBackground(new java.awt.Color(222, 222, 222));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setFocusable(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Employee 1");
        jLabel5.setAlignmentY(0.0F);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        Console.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 20));

        jPanel5.setBackground(new java.awt.Color(222, 222, 222));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setFocusable(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Employee 2");
        jLabel7.setAlignmentY(0.0F);
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        Console.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 130, 20));

        jPanel6.setBackground(new java.awt.Color(222, 222, 222));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setFocusable(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Baggage on plane");
        jLabel8.setAlignmentY(0.0F);
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        Console.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 20));

        recordButton.setBackground(new java.awt.Color(0, 0, 51));
        recordButton.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        recordButton.setForeground(new java.awt.Color(255, 255, 255));
        recordButton.setBorderPainted(false);
        recordButton.setContentAreaFilled(false);
        recordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordButtonActionPerformed(evt);
            }
        });
        Console.add(recordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 40, 40));
        Console.add(jLabelLcorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 400, -1, -1));
        Console.add(jLabelRcorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 400, -1, -1));

        jProgressBar2.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jProgressBar2.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar2.setMaximum(8);
        jProgressBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jProgressBar2.setString("");
        jProgressBar2.setStringPainted(true);
        Console.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setMaximum(80);
        jProgressBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);
        Console.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        getContentPane().add(Console, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Se crean los pasajeros que van a estar dejando maletas y a los
     * empleados que estarán recogiéndolas.
     */
    public final void initialize() {
        for (int i=0; i<40; i++) {      
            if (i<=1) {
                Employee e = new Employee(belt, passage);
                if (i==0) {
                    e.setID("Jorge");
                    //Se muestra la actividad de Jorge en un JTextArea.
                    e.setActivity(jTextAreaEmployee1);
                    jLabel5.setText(e.getID());
                    e.setPlane(plane);
                } else {
                    e.setID("Dani");
                    //Se muestra la actividad de Dani en un JTextArea.
                    e.setActivity(jTextAreaEmployee2);
                    jLabel7.setText(e.getID());
                    e.setPlane(plane);
                }
                e.start();   
            }           
            Passenger p = new Passenger("Passenger"+(i+1), belt);
            p.start();
        }
    }
    
    /**
     * @return el contenido del JTextArea relacionado con la cinta.
     */
    public String getBelt() {
        return jTextAreaBelt.getText();
    }
    
    /**
     * @return el contenido del JTextArea relacionado con el avión.
     */
    public String getPlane() {
        return jTextAreaPlane.getText();
    }
    
    /**
     * Se parará al empleado 1 (Jorge), con el contexto de estar descansando.
     * @param evt 
     */
    private void emp1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp1ButtonActionPerformed
        if(buttonPressed1) {
            JOptionPane.showMessageDialog(this, "No activity", "Error", JOptionPane.ERROR_MESSAGE);
            buttonPressed2 = false;
        } else if (!buttonPressed2) {
            buttonPressed2 = true;
            passage.stop("jButton2");
            jTextAreaEmployee1.setText("Resting.");
        } else {
            buttonPressed2 = false;
            passage.resume("jButton2");
        }
    }//GEN-LAST:event_emp1ButtonActionPerformed

    /**
     * Se parará al empleado 2 (Dani), con el contexto de estar descansando.
     * @param evt 
     */
    private void emp2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp2ButtonActionPerformed
        if(buttonPressed1) {
            JOptionPane.showMessageDialog(this, "No activity", "Error", JOptionPane.ERROR_MESSAGE);
            buttonPressed2 = false;
        } else if (!buttonPressed3) {
            buttonPressed3 = true;
            passage.stop("jButton3");
            jTextAreaEmployee2.setText("Resting.");
        } else {
            buttonPressed3 = false;
            passage.resume("jButton3");
        }
    }//GEN-LAST:event_emp2ButtonActionPerformed

    /**
     * Se pararán a todos.
     * @param evt 
     */
    private void globalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalButtonActionPerformed
        if (!buttonPressed1) {
            buttonPressed1 = true;
            buttonPressed2 = true;
            buttonPressed3 = true;
            passage.stop("jButton1");
            passage.stop("jButton2");
            passage.stop("jButton3");
            jTextAreaEmployee1.setText("Resting.");
            jTextAreaEmployee2.setText("Resting.");
            jPanelGlobal.setBackground(Color.GREEN);       
        } else {
            buttonPressed1 = false;
            buttonPressed2 = false;
            buttonPressed3 = false;
            passage.resume("jButton1");
            passage.resume("jButton2");
            passage.resume("jButton3");
            jPanelGlobal.setBackground(Color.RED);
        }
    }//GEN-LAST:event_globalButtonActionPerformed

    /**
     * Abrirá el historial de eventos.
     * @param evt 
     */
    private void recordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordButtonActionPerformed
        try {
            File fileObject = new File("Record.txt");
            Desktop.getDesktop().open(fileObject); 
        } catch (IOException ex) {}             
    }//GEN-LAST:event_recordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocalConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Console;
    private javax.swing.JButton emp1Button;
    private javax.swing.JButton emp2Button;
    private javax.swing.JButton globalButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLcorner;
    private javax.swing.JLabel jLabelRcorner;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jPanelBelt;
    private javax.swing.JScrollPane jPanelEmp1;
    private javax.swing.JScrollPane jPanelEmp2;
    private javax.swing.JPanel jPanelGlobal;
    private javax.swing.JScrollPane jPanelPlane;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JTextArea jTextAreaBelt;
    private javax.swing.JTextArea jTextAreaEmployee1;
    private javax.swing.JTextArea jTextAreaEmployee2;
    private javax.swing.JTextArea jTextAreaPlane;
    private javax.swing.JButton recordButton;
    // End of variables declaration//GEN-END:variables
}
