package remote;

/**
 * Consola remota. Esta interfaz mostrará los datos que le envíe el servidor
 * a su cliente asociado.
 * @author jorge
 */
public class RemoteConsole extends javax.swing.JFrame {
 
    /**
     * Constructor.
     */
    public RemoteConsole() {
        initComponents();     
        setSize(430, 300);    
        Console.setSize(430, 300);
    }

    /**
     * Muestra los datos de la cinta enviados por el servidor en la interfaz.
     * @param response respuesta del servidor respecto a la cinta.
     */
    public void setBelt(String response) {
        jTextArea1.setText(response);
    }
    
    /**
     * Muestra los datos del avión enviados por el servidor en la interfaz.
     * @param response respuesta del servidor respecto al avión.
     */
    public void setPlane(String response) {
        jTextArea2.setText(response);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Console = new javax.swing.JPanel();
        jPanelBelt = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelPlane = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/clientIcon.png")).getImage());
        setResizable(false);

        Console.setBackground(new java.awt.Color(153, 0, 0));
        Console.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBelt.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jPanelBelt.setFocusable(false);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(102, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextArea1.setFocusable(false);
        jPanelBelt.setViewportView(jTextArea1);

        Console.add(jPanelBelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 340, 50));

        jPanelPlane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(102, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setFocusable(false);
        jPanelPlane.setViewportView(jTextArea2);

        Console.add(jPanelPlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 340, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jLabel1.setText("Baggage on belt");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 1, -1, -1));

        Console.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 42, 120, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jLabel2.setText("Baggage on plane");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 1, -1, -1));

        Console.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 153, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Console, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Console, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoteConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoteConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoteConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoteConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoteConsole().setVisible(true);
            }
        });
    }
//<editor-fold defaultstate="collapsed" desc=" Variables declaration (Do not modify)">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Console;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jPanelBelt;
    private javax.swing.JScrollPane jPanelPlane;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>